# Generated by Django 4.2.3 on 2023-07-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbuddy', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
