# Generated by Django 4.2.3 on 2023-07-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobbuddy', '0003_job_posting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('INTERNSHIP', 'INTERNSHIP'), ('ENTRY_LEVEL', 'ENTRY_LEVEL'), ('MID_LEVEL', 'MID_LEVEL'), ('SENIOR_LEVEL', 'SENIOR_LEVEL')], default=('INTERNSHIP', 'INTERNSHIP'), max_length=64),
        ),
    ]
